name: Adhoc DAO Member Fetch
on:
  workflow_dispatch:
    inputs:
      address:
        description: 'ERC20 Contract Address'
        required: true
        type: string
jobs:
  fetch_token_holders:
    uses: mindthealgorithm/daois/.github/workflows/holders.yml@main
    with:
      address: ${{ inputs.address }}
    secrets:
      ETHEREUM_NODE: ${{ secrets.ETHEREUM_NODE }}
