name: Adhoc DAO update
on:
  workflow_dispatch:
    inputs:
      address:
        description: 'ERC20 Contract Address'
        required: true
        type: string
        default: ''
jobs:
  adhoc_update:
    runs-on: ubuntu-latest
    steps:
      - uses: ./daois.yaml
        with:
          address: ${{ inputs.address }}
