name: BetaDAO Members
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
jobs:
  betadao:
    uses: jcinis/daois/.github/workflows/holders.yml@main
    with:
      address: "0xE2E38C81531c163eD921f86BF6c0D044957f8E23"
    secrets:
      ETHEREUM_NODE: ${{secrets.ETHEREUM_NODE}}
