name: BetaDAO
on:
  workflow_dispatch:
jobs:
  cache_dao_members:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/daois
        with:
          address: "0xE2E38C81531c163eD921f86BF6c0D044957f8E23"
