name: echo
on:
  workflow_call:
    inputs:
      message:
        description: 'Message to print'
        default: 'Hello, this is an action!'
        required: false
        type: string
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo ${{inputs.message}}
