name: Update members
on:
  workflow_dispatch:
    inputs:
      address:
        description: 'ERC20 Contract Address'
        default: ''
        required: true
jobs:
  update_members:
    runs-on: ubuntu-latest
    steps:
    - name: Find token holders
      run: |
        echo "${{ github.event.inputs.address }}"
        echo "${{ secrets.ETHEREUM_NODE }}"
